wallpaper {
    monitor = eDP-1
    path = /mnt/space/pictures/Artwork/wallpaper/water.jpg
    fit_mode = cover
}
wallpaper {
    monitor = 
    path = /mnt/space/pictures/Artwork/wallpaper/orange-moss.jpg
    fit_mode = cover
}
splash = false
