-- Generated by HyprMod

-- Settings
hl.config({
    dwindle = {
        force_split = 2,
    },
})

-- Bezier curves
hl.curve("almostLinear", { type = "bezier", points = { {0.5, 0.5}, {0.75, 1.0} } })
hl.curve("easeOutQuint", { type = "bezier", points = { {0.23, 1.0}, {0.32, 1.0} } })
hl.curve("quick", { type = "bezier", points = { {0.15, 0.0}, {0.1, 1.0} } })

-- Animations
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 15.0,
    bezier = "linear",
})
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 4.0,
    bezier = "default",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 4.0,
    bezier = "default",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 10.0,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 8.0,
    bezier = "quick",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5.4,
    bezier = "almostLinear",
})
